Repository hey-api/openapi-ts, pull requests merged in 2025-08, with the labels that each got.

#2407 fix: add a check to prevent a recursion issue when asClass is true and the schema contains a tag and an operationId with the same name (e.g. "TodoItem")
  .changeset/hip-teachers-kiss.md
  packages/openapi-ts/src/plugins/@hey-api/sdk/plugin.ts
Labels: bug 🔥, size:XS, lgtm

#2399 feat(tanstack-query): introduce meta, and operation meta tags
  .changeset/eight-pillows-wash.md
  docs/openapi-ts/plugins/tanstack-query.md
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/@tanstack/angular-query-experimental.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/@tanstack/react-query.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/@tanstack/solid-query.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/@tanstack/svelte-query.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/@tanstack/vue-query.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/client/client.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/client/index.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/client/types.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/client/utils.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/core/auth.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/core/bodySerializer.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/core/params.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/core/pathSerializer.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/core/types.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/index.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/sdk.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/plugins/@tanstack/meta/types.gen.ts
  packages/openapi-ts-tests/main/test/plugins/@tanstack/meta-function.test.ts
  packages/openapi-ts/src/plugins/@tanstack/angular-query-experimental/config.ts
  packages/openapi-ts/src/plugins/@tanstack/angular-query-experimental/types.d.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/infiniteQueryOptions.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/meta.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/mutationOptions.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/queryOptions.ts
  packages/openapi-ts/src/plugins/@tanstack/react-query/config.ts
  packages/openapi-ts/src/plugins/@tanstack/react-query/types.d.ts
  packages/openapi-ts/src/plugins/@tanstack/solid-query/config.ts
  packages/openapi-ts/src/plugins/@tanstack/solid-query/types.d.ts
  packages/openapi-ts/src/plugins/@tanstack/svelte-query/config.ts
  packages/openapi-ts/src/plugins/@tanstack/svelte-query/types.d.ts
  packages/openapi-ts/src/plugins/@tanstack/vue-query/config.ts
  packages/openapi-ts/src/plugins/@tanstack/vue-query/types.d.ts
Labels: size:XXL, lgtm

#2415 fix: cjs build
  packages/openapi-ts/src/generate/client.ts
Labels: bug 🔥, size:S

#2416 fix(tanstack-query): set correct name for pagination parameters in infinite query options
  .changeset/perfect-berries-beam.md
  packages/openapi-ts/src/ir/__tests__/pagination.test.ts
  packages/openapi-ts/src/ir/pagination.ts
  packages/openapi-ts/src/ir/parameter.ts
Labels: bug 🔥, size:M

#2432 chore: add renovate
  renovate.json
Labels: dependencies, size:XS

#2453 docs: add Algolia search
  .github/workflows/ci.yml
  .nvmrc
  docs/.vitepress/config/shared.ts
  docs/index.md
  docs/openapi-ts/get-started.md
  docs/package.json
  docs/tsconfig.json
  package.json
  packages/openapi-ts/README.md
  pnpm-lock.yaml
Labels: docs 📃, size:M

#2454 docs: add llm-friendly output
  docs/.vitepress/config/shared.ts
  docs/package.json
  examples/openapi-ts-axios/package.json
  examples/openapi-ts-fastify/package.json
  examples/openapi-ts-fetch/package.json
  examples/openapi-ts-nuxt/package.json
  examples/openapi-ts-sample/package.json
  examples/openapi-ts-tanstack-react-query/package.json
  examples/openapi-ts-tanstack-svelte-query/package.json
  examples/openapi-ts-tanstack-vue-query/package.json
  packages/config-vite-base/package.json
  packages/nuxt/package.json
  packages/vite-plugin/package.json
  pnpm-lock.yaml
Labels: docs 📃, size:M

#2463 docs: add sr-only css
  docs/.vitepress/theme/custom.css
  docs/openapi-ts/clients/angular.md
  docs/openapi-ts/clients/angular/v19.md
  docs/openapi-ts/clients/axios.md
  docs/openapi-ts/clients/nuxt.md
  docs/openapi-ts/plugins/angular.md
  docs/openapi-ts/plugins/angular/v19.md
  docs/openapi-ts/plugins/fastify.md
  docs/openapi-ts/plugins/tanstack-query.md
  docs/openapi-ts/plugins/valibot.md
  docs/openapi-ts/plugins/zod.md
  docs/openapi-ts/plugins/zod/mini.md
  docs/openapi-ts/plugins/zod/v3.md
Labels: size:M

#2464 docs: prefix sr-only version with v
  docs/openapi-ts/clients/angular.md
  docs/openapi-ts/clients/angular/v19.md
  docs/openapi-ts/clients/axios.md
  docs/openapi-ts/clients/nuxt.md
  docs/openapi-ts/plugins/angular.md
  docs/openapi-ts/plugins/angular/v19.md
  docs/openapi-ts/plugins/fastify.md
  docs/openapi-ts/plugins/tanstack-query.md
  docs/openapi-ts/plugins/valibot.md
  docs/openapi-ts/plugins/zod.md
  docs/openapi-ts/plugins/zod/v3.md
Labels: size:S

#2481 fix(parser): cache parent to children nodes
  .changeset/khaki-rabbits-explain.md
  packages/openapi-ts-tests/main/test/openapi-ts.config.ts
  packages/openapi-ts-tests/main/test/performance.test.ts
  packages/openapi-ts/src/index.ts
  packages/openapi-ts/src/openApi/shared/utils/graph.ts
  packages/openapi-ts/src/openApi/shared/utils/graphDebug.ts
  packages/openapi-ts/src/utils/logger.ts
Labels: size:L

#2485 Add ReadMe API Registry input support
  .changeset/soft-wolves-develop.md
  docs/openapi-ts/configuration/input.md
  examples/openapi-ts-openai/src/client/types.gen.ts
  packages/openapi-ts/src/config/__tests__/input.test.ts
  packages/openapi-ts/src/config/input.ts
  packages/openapi-ts/src/types/config.d.ts
  packages/openapi-ts/src/types/input.d.ts
  packages/openapi-ts/src/utils/__tests__/readme.test.ts
  packages/openapi-ts/src/utils/readme.ts
Labels: feature 🚀, size:XL

#2479 Reducing security schema duplicates in OpenAPI parser
  .changeset/ninety-kings-confess.md
  packages/openapi-ts/src/openApi/2.0.x/parser/__tests__/operation.test.ts
  packages/openapi-ts/src/openApi/2.0.x/parser/operation.ts
  packages/openapi-ts/src/openApi/3.0.x/parser/__tests__/operation.test.ts
  packages/openapi-ts/src/openApi/3.0.x/parser/operation.ts
  packages/openapi-ts/src/openApi/3.1.x/parser/__tests__/operation.test.ts
  packages/openapi-ts/src/openApi/3.1.x/parser/operation.ts
Labels: internal ⚙️, size:L, lgtm

#2493 docs(zod): document iso datetimes
  docs/openapi-ts/configuration.md
  docs/openapi-ts/configuration/input.md
  docs/openapi-ts/plugins/zod.md
  docs/openapi-ts/plugins/zod/mini.md
  docs/openapi-ts/plugins/zod/v3.md
  docs/package.json
  packages/openapi-ts-tests/main/test/openapi-ts.config.ts
  pnpm-lock.yaml
Labels: docs 📃, size:L

#2498 docs: add Falso and Chance pages
  docs/.vitepress/config/en.ts
  docs/openapi-ts/mocks.md
  docs/openapi-ts/plugins.md
  docs/openapi-ts/plugins/chance.md
  docs/openapi-ts/plugins/falso.md
  packages/openapi-ts/README.md
Labels: size:M

#2500 fix(angular-client): ensure default GET method is applied correctly in request options
  .changeset/lovely-keys-attend.md
  packages/openapi-ts/src/plugins/@hey-api/client-angular/bundle/client.ts
Labels: bug 🔥, client, size:S, lgtm

#2502 Fix: Typescript union types for openapi 3.1
  .changeset/grumpy-rings-decide.md
  packages/openapi-ts-tests/main/test/3.1.x.test.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/union-types/index.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/union-types/types.gen.ts
  packages/openapi-ts-tests/specs/3.1.x/union-types.json
  packages/openapi-ts/src/openApi/3.1.x/parser/schema.ts
Labels: bug 🔥, size:M, lgtm

#2516 feat(parser): track webhooks in OpenAPI 3.1
  .changeset/dirty-dots-decide.md
  .changeset/three-meals-pay.md
  .changeset/wild-pants-act.md
  .gitignore
  package.json
  packages/openapi-ts-tests/main/test/3.1.x.test.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/webhooks/index.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/webhooks/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/webhooks/valibot.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/webhooks/zod.gen.ts
  packages/openapi-ts-tests/main/test/openapi-ts.config.ts
  packages/openapi-ts-tests/specs/3.1.x/zoom-video-sdk.json
  packages/openapi-ts/src/debug/graph.ts
  packages/openapi-ts/src/debug/index.ts
  packages/openapi-ts/src/debug/ir.ts
  packages/openapi-ts/src/ir/types.d.ts
  packages/openapi-ts/src/openApi/2.0.x/parser/__tests__/operation.test.ts
  packages/openapi-ts/src/openApi/2.0.x/parser/index.ts
  packages/openapi-ts/src/openApi/2.0.x/parser/operation.ts
  packages/openapi-ts/src/openApi/3.0.x/parser/__tests__/operation.test.ts
  packages/openapi-ts/src/openApi/3.0.x/parser/index.ts
  packages/openapi-ts/src/openApi/3.0.x/parser/operation.ts
  packages/openapi-ts/src/openApi/3.1.x/parser/__tests__/operation.test.ts
  packages/openapi-ts/src/openApi/3.1.x/parser/index.ts
  packages/openapi-ts/src/openApi/3.1.x/parser/operation.ts
  packages/openapi-ts/src/openApi/3.1.x/parser/webhook.ts
  packages/openapi-ts/src/openApi/shared/utils/graph.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/api.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/config.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/plugin.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/types.d.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/webhook.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/webhooks.ts
  packages/openapi-ts/src/plugins/shared/types/instance.d.ts
  packages/openapi-ts/src/plugins/shared/utils/instance.ts
  packages/openapi-ts/src/plugins/valibot/config.ts
  packages/openapi-ts/src/plugins/valibot/plugin.ts
  packages/openapi-ts/src/plugins/valibot/types.d.ts
  packages/openapi-ts/src/plugins/valibot/webhook.ts
  packages/openapi-ts/src/plugins/zod/api.ts
  packages/openapi-ts/src/plugins/zod/config.ts
  packages/openapi-ts/src/plugins/zod/mini/plugin.ts
  packages/openapi-ts/src/plugins/zod/shared/webhook.ts
  packages/openapi-ts/src/plugins/zod/types.d.ts
  packages/openapi-ts/src/plugins/zod/v3/plugin.ts
  packages/openapi-ts/src/plugins/zod/v4/plugin.ts
Labels: feature 🚀, size:XXL

#2527 docs: add a new image
  docs/public/blueprint.png
  docs/public/images/blueprint-300w.png
  docs/public/images/blueprint-640w.png
  docs/public/images/cella-logo-wordmark.svg
  docs/public/images/fastapi-logo-wordmark.svg
  docs/public/images/scalar-logo-wordmark.svg
  docs/scripts/optimize-images.js
  packages/nuxt/README.md
  packages/openapi-ts-tests/main/test/openapi-ts.config.ts
  packages/openapi-ts/README.md
  packages/vite-plugin/README.md
Labels: size:M

#2528 docs: add svg logo
  docs/.vitepress/config/shared.ts
  docs/.vitepress/theme/custom.css
  docs/index.md
  docs/public/images/logo-16w.png
  docs/public/images/logo-300w.png
  docs/public/images/logo-32w.png
  docs/public/images/logo-48w.png
  docs/public/images/logo-640w.png
  docs/public/images/logo-astronaut-300w.png
  docs/public/logo-astronaut.png
  docs/public/logo-dark.svg
  docs/public/logo-light.svg
  docs/public/logo.png
  docs/public/logo.svg
  docs/scripts/optimize-images.js
  packages/nuxt/README.md
  packages/vite-plugin/README.md
Labels: docs 📃, size:M

#2535 feat(client): added angular, axios, fetch, next & nuxt client type export for external typing purposes;
  .changeset/ninety-glasses-rule.md
  packages/openapi-ts/src/index.ts
  packages/openapi-ts/src/plugins/@hey-api/client-angular/index.ts
  packages/openapi-ts/src/plugins/@hey-api/client-axios/index.ts
  packages/openapi-ts/src/plugins/@hey-api/client-fetch/index.ts
  packages/openapi-ts/src/plugins/@hey-api/client-next/index.ts
  packages/openapi-ts/src/plugins/@hey-api/client-nuxt/index.ts
Labels: feature 🚀, client, size:S, lgtm

#2541 feat: add support for generating const enum as enum type
  .changeset/itchy-kiwis-repeat.md
  packages/openapi-ts-tests/main/test/2.0.x.test.ts
  packages/openapi-ts-tests/main/test/3.0.x.test.ts
  packages/openapi-ts-tests/main/test/3.1.x.test.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/enum-names-values-typescript-const/index.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/enum-names-values-typescript-const/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/enum-names-values-typescript-const/index.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/enum-names-values-typescript-const/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/enum-names-values-typescript-const/index.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/enum-names-values-typescript-const/types.gen.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/plugin-legacy.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/plugin.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/types.d.ts
  packages/openapi-ts/src/tsc/types.ts
Labels: feature 🚀, size:L, lgtm

#2566 ci: add custom bot
  .changeset/__tests__/changelog.test.ts
  .github/workflows/release.yml
  __tests__/changelog.test.ts
Labels: size:L

#2545 docs: fix config file name
  docs/openapi-ts/get-started.md
Labels: size:XS

#2569 feat(tanstack-query): add hooks options
  .changeset/changelog.js
  packages/openapi-ts-tests/main/test/openapi-ts.config.ts
  packages/openapi-ts/README.md
  packages/openapi-ts/src/plugins/@pinia/colada/queryOptions.ts
  packages/openapi-ts/src/plugins/@tanstack/angular-query-experimental/config.ts
  packages/openapi-ts/src/plugins/@tanstack/angular-query-experimental/types.d.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/infiniteQueryOptions.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/mutationOptions.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/plugin.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/queryOptions.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/types.d.ts
  packages/openapi-ts/src/plugins/@tanstack/query-core/useQuery.ts
  packages/openapi-ts/src/plugins/@tanstack/react-query/config.ts
  packages/openapi-ts/src/plugins/@tanstack/react-query/types.d.ts
  packages/openapi-ts/src/plugins/@tanstack/solid-query/config.ts
  packages/openapi-ts/src/plugins/@tanstack/solid-query/types.d.ts
  packages/openapi-ts/src/plugins/@tanstack/svelte-query/config.ts
  packages/openapi-ts/src/plugins/@tanstack/svelte-query/types.d.ts
  packages/openapi-ts/src/plugins/@tanstack/vue-query/config.ts
  packages/openapi-ts/src/plugins/@tanstack/vue-query/types.d.ts
  packages/openapi-ts/src/plugins/shared/utils/operation.ts
Labels: size:L

#2574 fix: update peer dependencies to be more permissible
  .changeset/hip-zoos-juggle.md
  .github/workflows/ci.yml
  .gitignore
  .prettierignore
  eslint.config.js
  package.json
  packages/codegen-core/package.json
  packages/custom-client/package.json
  packages/nuxt/package.json
  packages/openapi-ts-tests/main/.gitignore
  packages/openapi-ts-tests/main/package.json
  packages/openapi-ts-tests/main/test/e2e/assets/index.html
  packages/openapi-ts-tests/main/test/e2e/assets/main-angular-module.ts
  packages/openapi-ts-tests/main/test/e2e/assets/main-angular.ts
  packages/openapi-ts-tests/main/test/e2e/assets/main.ts
  packages/openapi-ts-tests/main/test/e2e/client.angular.test.ts
  packages/openapi-ts-tests/main/test/e2e/client.axios.test.ts
  packages/openapi-ts-tests/main/test/e2e/client.fetch.test.ts
  packages/openapi-ts-tests/main/test/e2e/client.node.test.ts
  packages/openapi-ts-tests/main/test/e2e/client.xhr.test.ts
  packages/openapi-ts-tests/main/test/e2e/scripts/angular.ts
  packages/openapi-ts-tests/main/test/e2e/scripts/browser.ts
  packages/openapi-ts-tests/main/test/e2e/scripts/cleanup.ts
  packages/openapi-ts-tests/main/test/e2e/scripts/compileWithTypescript.ts
  packages/openapi-ts-tests/main/test/e2e/scripts/copyAsset.ts
  packages/openapi-ts-tests/main/test/e2e/scripts/generateClient.ts
  packages/openapi-ts-tests/main/test/e2e/scripts/server.ts
  packages/openapi-ts-tests/main/test/e2e/v2.angular.test.ts
  packages/openapi-ts-tests/main/test/e2e/v2.axios.test.ts
  packages/openapi-ts-tests/main/test/e2e/v2.fetch.test.ts
  packages/openapi-ts-tests/main/test/e2e/v2.node.test.ts
  packages/openapi-ts-tests/main/test/e2e/v2.xhr.test.ts
  packages/openapi-ts-tests/main/test/e2e/v3.angular.test.ts
  packages/openapi-ts-tests/main/test/e2e/v3.axios.test.ts
  packages/openapi-ts-tests/main/test/e2e/v3.fetch.test.ts
  packages/openapi-ts-tests/main/test/e2e/v3.node.test.ts
  packages/openapi-ts-tests/main/test/e2e/v3.xhr.test.ts
  packages/openapi-ts-tests/main/tsconfig.json
  packages/openapi-ts-tests/main/vitest.config.e2e.ts
  packages/openapi-ts-tests/main/vitest.config.ts
  packages/openapi-ts-tests/zod/v3/package.json
  packages/openapi-ts-tests/zod/v4/package.json
  packages/openapi-ts/package.json
  packages/openapi-ts/tsconfig.json
  packages/vite-plugin/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: dependencies, size:XXL
