Repository hey-api/openapi-ts, pull requests merged in 2025-09, with the labels that each got.

#2572 fix(angular): allow `httpResource` to skip requests when `undefined` is returned
  .changeset/sweet-dragons-reflect.md
  examples/openapi-ts-angular-common/src/client/@angular/common/http/resources.gen.ts
  examples/openapi-ts-angular-common/src/client/client/client.gen.ts
  examples/openapi-ts-angular-common/src/client/client/types.gen.ts
  examples/openapi-ts-angular-common/src/client/core/serverSentEvents.gen.ts
  examples/openapi-ts-angular-common/src/client/core/types.gen.ts
  examples/openapi-ts-angular-common/src/client/core/utils.gen.ts
  examples/openapi-ts-angular/src/client/client/client.gen.ts
  examples/openapi-ts-angular/src/client/client/types.gen.ts
  examples/openapi-ts-angular/src/client/core/serverSentEvents.gen.ts
  examples/openapi-ts-angular/src/client/core/types.gen.ts
  examples/openapi-ts-angular/src/client/core/utils.gen.ts
  packages/openapi-ts/src/plugins/@angular/common/httpResources.ts
Labels: bug 🔥, client, size:XXL

#2588 chore: add changeset
  .changeset/sharp-rules-eat.md
Labels: size:XS

#2593 fix(pinia-colada): optional `options` in mutation factory
  .changeset/optional-options-in-mutation-factory.md
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/fetch/@pinia/colada.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Defaults.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Descriptions.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Duplicate.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Error.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Header.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Non-Ascii-æøåÆØÅöôêÊ.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Parameters.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Response.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Simple.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/default.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/fetch/@pinia/colada.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Complex.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Defaults.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Deprecated.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Descriptions.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Duplicate.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Error.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/FormData.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Header.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Non-Ascii-æøåÆØÅöôêÊ.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Parameters.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/RequestBody.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Response.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Simple.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Upload.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/default.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/multipart.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/fetch/@pinia/colada.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Complex.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Defaults.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Deprecated.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Descriptions.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Duplicate.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Error.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/FormData.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Header.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Non-Ascii-æøåÆØÅöôêÊ.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Parameters.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/RequestBody.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Response.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Simple.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/Upload.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/default.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@pinia/colada/group-by-tag/@pinia/colada/multipart.gen.ts
  packages/openapi-ts/src/plugins/@pinia/colada/mutationOptions.ts
Labels: bug 🔥, size:L, lgtm

#2600 fix(client-axios): ensures falsy request body can be serialized
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@tanstack/angular-query-experimental/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@tanstack/react-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@tanstack/solid-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@tanstack/svelte-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/2.0.x/plugins/@tanstack/vue-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/content-types/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/parameter-explode-false-axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@tanstack/angular-query-experimental/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@tanstack/react-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@tanstack/solid-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@tanstack/svelte-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.0.x/plugins/@tanstack/vue-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-axios/base-url-false/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-axios/base-url-number/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-axios/base-url-strict/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-axios/base-url-string/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-axios/clean-false/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-axios/default/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-axios/sdk-client-optional/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-axios/sdk-client-required/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-axios/tsconfig-nodenext-sdk/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/content-types/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/parameter-explode-false-axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@tanstack/angular-query-experimental/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@tanstack/react-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@tanstack/solid-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@tanstack/svelte-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/plugins/@tanstack/vue-query/axios/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/sse-axios/client/client.gen.ts
  packages/openapi-ts/src/plugins/@hey-api/client-axios/__tests__/client.test.ts
  packages/openapi-ts/src/plugins/@hey-api/client-axios/bundle/client.ts
Labels: bug 🔥, client, size:XL, lgtm

#2598 feat(pinia-colada): implicit `$fetch` for `client-nuxt` (hide `composable`)
  .changeset/implicit-fetch.md
  docs/openapi-ts/clients/nuxt.md
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/base-url-false/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/base-url-false/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/base-url-number/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/base-url-number/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/base-url-strict/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/base-url-strict/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/base-url-string/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/base-url-string/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/clean-false/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/clean-false/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/clean-false/sdk.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/default/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/default/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/default/sdk.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/sdk-client-optional/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/sdk-client-optional/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/sdk-client-optional/sdk.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/sdk-client-required/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/sdk-client-required/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/sdk-client-required/sdk.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/tsconfig-nodenext-sdk/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/tsconfig-nodenext-sdk/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/clients/@hey-api/client-nuxt/tsconfig-nodenext-sdk/sdk.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/sse-nuxt/client/client.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/sse-nuxt/client/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/sse-nuxt/sdk.gen.ts
  packages/openapi-ts/src/plugins/@hey-api/client-nuxt/bundle/client.ts
  packages/openapi-ts/src/plugins/@hey-api/client-nuxt/bundle/types.ts
  packages/openapi-ts/src/plugins/@hey-api/sdk/plugin.ts
  packages/openapi-ts/src/plugins/@hey-api/sdk/typeOptions.ts
  packages/openapi-ts/src/plugins/@pinia/colada/mutationOptions.ts
  packages/openapi-ts/src/plugins/@pinia/colada/queryKey.ts
  packages/openapi-ts/src/plugins/@pinia/colada/queryOptions.ts
  packages/openapi-ts/src/plugins/@pinia/colada/utils.ts
Labels: feature 🚀, client, size:XL, lgtm

#2615 ci: fix lockfile issue with changesets
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/release.yml
Labels: size:S

#2627 chore: add changeset
  .changeset/many-ravens-wave.md
Labels: size:XS

#2629 feat(typescript): add topType option allowing to choose any over unknown
  .changeset/happy-kangaroos-shake.md
  packages/openapi-ts-tests/main/test/3.1.x.test.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/additional-properties-true-any/index.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/additional-properties-true-any/types.gen.ts
  packages/openapi-ts-tests/main/test/openapi-ts.config.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/config.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/plugin.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/types.d.ts
Labels: feature 🚀, size:M

#2630 fix(typescript): handle string and binary string in composite keywords
  .changeset/purple-elephants-lie.md
  packages/openapi-ts-tests/main/test/3.1.x.test.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/pattern-properties/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/string-with-format/index.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/string-with-format/types.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/string-with-format/valibot.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/3.1.x/string-with-format/zod.gen.ts
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v2/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_angular/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_angular_transform/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_angular_tree_shakeable/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_angular_tree_shakeable_transform/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_axios/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_axios_transform/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_client/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_client_transform/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_date/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_enums_typescript/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_node/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_node_transform/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_services_filter/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_services_name/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_transform/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_tree_shakeable/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_xhr/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/__snapshots__/test/generated/v3_xhr_transform/types.gen.ts.snap
  packages/openapi-ts-tests/main/test/openapi-ts.config.ts
  packages/openapi-ts-tests/specs/3.1.x/string-with-format.yaml
  packages/openapi-ts/src/plugins/@hey-api/typescript/operation.ts
  packages/openapi-ts/src/plugins/@hey-api/typescript/plugin.ts
  packages/openapi-ts/src/tsc/typedef.ts
Labels: bug 🔥, size:M

#2667 fix(parser): bump support for openapi 3.1.2
  .changeset/gorgeous-spiders-build.md
  packages/openapi-ts-tests/main/test/openapi-ts.config.ts
  packages/openapi-ts/src/config/utils/package.ts
  packages/openapi-ts/src/openApi/3.1.x/types/spec.d.ts
  packages/openapi-ts/src/openApi/index.ts
  packages/openapi-ts/src/plugins/@hey-api/schemas/plugin.ts
Labels: bug 🔥, size:M
